import Header from "@/components/Header";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#55585c] absolute top-[-6rem] right-[11rem] h-[32rem] w-[32rem] rounded-full blur-[10rem]  -z-20 sm:w-[68rem]   "></div>
        <div className="bg-[#6c724f] absolute top-[-1rem] -z-20 left-[-35rem] h-[32rem] w-[32rem] rounded-full blur-[10rem] sm:w-[68rem] md:left-[-33rem] lg:left-[-28rem]  "></div>

        <ClerkProvider>
          <Header />

          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
